import '../entities/ingredient.dart';
import '../entities/meal_type.dart';
import '../entities/recipe.dart';

/// Community-contributed recipes shown in the Community tab, sourced from
/// the "50 High-Protein French-Inspired Meals" collection. Calories/protein/
/// carbs/fat are the curated per-portion values from that source (NOT
/// recomputed from ingredients — the app previously ran these through the
/// food-matching pipeline, but that produced inaccurate totals when an
/// ingredient's free-text name didn't resolve to a confident food match).
/// No fiber figure is provided by the source data.
List<Recipe> communityBreakfastRecipes() => [
  Recipe(
    name: 'Zucchini, Carrot & Cheese Tortilla',
    calories: 500,
    protein: 31,
    carbs: 39,
    fat: 24,
    portions: 1,
    mealType: MealType.breakfast,
    photoPath: 'assets/images/community_thumbnails/zucchini_carrot_cheese_tortilla.jpg',
    description: 'Slice zucchini thinly and grate carrot. Sauté zucchini in olive oil for 3–4 minutes. Beat eggs with carrot, salt, pepper and herbs. Pour over zucchini and cook until nearly set. Add cheese and place tortilla over the top. Fold in half and toast both sides until golden.',
    ingredients: [
      Ingredient(name: 'whole-wheat tortilla', quantity: '50 g'),
      Ingredient(name: 'eggs', quantity: '2 piece'),
      Ingredient(name: 'zucchini', quantity: '150 g'),
      Ingredient(name: 'carrot', quantity: '60 g'),
      Ingredient(name: 'grated mozzarella', quantity: '40 g'),
      Ingredient(name: 'olive oil', quantity: '1 tsp'),
      Ingredient(name: 'salt', quantity: ''),
      Ingredient(name: 'black pepper', quantity: ''),
      Ingredient(name: 'herbes de provence', quantity: ''),
    ],
  ),
  Recipe(
    name: 'High-Protein French Crêpes with Skyr & Berries',
    calories: 450,
    protein: 35,
    carbs: 55,
    fat: 8,
    portions: 1,
    mealType: MealType.breakfast,
    photoPath: 'assets/images/community_thumbnails/high_protein_french_crepes_with_skyr_berries.jpg',
    description: 'Whisk flour, egg, egg whites and milk. Rest batter for 10 minutes. Cook thin crêpes in a non-stick pan. Fill with skyr and berries. Drizzle with honey.',
    ingredients: [
      Ingredient(name: 'flour', quantity: '50 g'),
      Ingredient(name: 'egg', quantity: '1 piece'),
      Ingredient(name: 'egg whites', quantity: '100 g'),
      Ingredient(name: 'semi-skimmed milk', quantity: '100 ml'),
      Ingredient(name: 'plain skyr', quantity: '150 g'),
      Ingredient(name: 'strawberries or raspberries', quantity: '100 g'),
      Ingredient(name: 'honey', quantity: '1 tsp'),
      Ingredient(name: 'vanilla', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Croque-Madame with Turkey',
    calories: 520,
    protein: 45,
    carbs: 39,
    fat: 21,
    portions: 1,
    mealType: MealType.breakfast,
    photoPath: 'assets/images/community_thumbnails/croque_madame_with_turkey.jpg',
    description: 'Make a light béchamel with butter, flour and milk. Spread mustard on bread and add turkey and half the cheese. Close sandwich and spread béchamel on top. Add remaining Gruyère and bake at 200°C until golden. Fry egg and place on top.',
    ingredients: [
      Ingredient(name: 'slices whole-grain bread', quantity: '2 piece'),
      Ingredient(name: 'sliced turkey breast', quantity: '80 g'),
      Ingredient(name: 'gruyère', quantity: '30 g'),
      Ingredient(name: 'egg', quantity: '1 piece'),
      Ingredient(name: 'milk', quantity: '50 ml'),
      Ingredient(name: 'flour', quantity: '10 g'),
      Ingredient(name: 'butter', quantity: '5 g'),
      Ingredient(name: 'dijon mustard', quantity: ''),
      Ingredient(name: 'pepper', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Savory Breton Galette with Chicken & Egg',
    calories: 500,
    protein: 49,
    carbs: 38,
    fat: 17,
    portions: 1,
    mealType: MealType.breakfast,
    photoPath: 'assets/images/community_thumbnails/savory_breton_galette_with_chicken_egg.jpg',
    description: 'Mix buckwheat flour and water. Cook a thin galette. Add chicken, mushrooms and spinach. Crack egg into center. Add Gruyère. Fold four sides inward and cook until egg is set.',
    ingredients: [
      Ingredient(name: 'buckwheat flour', quantity: '50 g'),
      Ingredient(name: 'water', quantity: '120 ml'),
      Ingredient(name: 'cooked chicken breast', quantity: '100 g'),
      Ingredient(name: 'egg', quantity: '1 piece'),
      Ingredient(name: 'gruyère', quantity: '30 g'),
      Ingredient(name: 'mushrooms', quantity: '50 g'),
      Ingredient(name: 'spinach', quantity: '30 g'),
      Ingredient(name: 'pepper', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Skyr, Apple & Walnut French Breakfast Bowl',
    calories: 430,
    protein: 30,
    carbs: 48,
    fat: 14,
    portions: 1,
    mealType: MealType.breakfast,
    photoPath: 'assets/images/community_thumbnails/skyr_apple_walnut_french_breakfast_bowl.jpg',
    description: 'Dice apple. Toast oats and walnuts lightly. Put skyr in bowl. Add apple, oats and walnuts. Finish with cinnamon and honey.',
    ingredients: [
      Ingredient(name: 'plain skyr', quantity: '250 g'),
      Ingredient(name: 'apple', quantity: '1 piece'),
      Ingredient(name: 'walnuts', quantity: '20 g'),
      Ingredient(name: 'oats', quantity: '20 g'),
      Ingredient(name: 'cinnamon', quantity: ''),
      Ingredient(name: 'honey', quantity: '1 tsp'),
    ],
  ),
  Recipe(
    name: 'Omelette Provençale',
    calories: 420,
    protein: 38,
    carbs: 13,
    fat: 24,
    portions: 1,
    mealType: MealType.breakfast,
    photoPath: 'assets/images/community_thumbnails/omelette_provencale.jpg',
    description: 'Sauté mushrooms and tomatoes. Add spinach until wilted. Beat eggs and egg whites. Pour into pan. Add vegetables and goat cheese. Fold and cook until set.',
    ingredients: [
      Ingredient(name: 'eggs', quantity: '3 piece'),
      Ingredient(name: 'egg whites', quantity: '100 g'),
      Ingredient(name: 'tomatoes', quantity: '100 g'),
      Ingredient(name: 'mushrooms', quantity: '50 g'),
      Ingredient(name: 'spinach', quantity: '50 g'),
      Ingredient(name: 'goat cheese', quantity: '20 g'),
      Ingredient(name: 'olive oil', quantity: '1 tsp'),
      Ingredient(name: 'herbes de provence', quantity: ''),
    ],
  ),
  Recipe(
    name: 'French Toast with Skyr & Strawberries',
    calories: 450,
    protein: 29,
    carbs: 53,
    fat: 12,
    portions: 1,
    mealType: MealType.breakfast,
    photoPath: 'assets/images/community_thumbnails/french_toast_with_skyr_strawberries.jpg',
    description: 'Whisk eggs, milk, cinnamon and vanilla. Soak bread briefly. Cook until golden. Serve with skyr and strawberries. Add honey.',
    ingredients: [
      Ingredient(name: 'thick slices whole-grain bread', quantity: '2 piece'),
      Ingredient(name: 'eggs', quantity: '2 piece'),
      Ingredient(name: 'milk', quantity: '100 ml'),
      Ingredient(name: 'skyr', quantity: '100 g'),
      Ingredient(name: 'strawberries', quantity: '100 g'),
      Ingredient(name: 'cinnamon', quantity: ''),
      Ingredient(name: 'vanilla', quantity: ''),
      Ingredient(name: 'honey', quantity: '1 tsp'),
    ],
  ),
  Recipe(
    name: 'Smoked Salmon & Cottage Cheese Tartine',
    calories: 410,
    protein: 37,
    carbs: 34,
    fat: 15,
    portions: 1,
    mealType: MealType.breakfast,
    photoPath: 'assets/images/community_thumbnails/smoked_salmon_cottage_cheese_tartine.jpg',
    description: 'Toast bread. Spread cottage cheese. Add smoked salmon. Top with cucumber, dill and lemon. Finish with pepper.',
    ingredients: [
      Ingredient(name: 'slices rye or whole-grain bread', quantity: '2 piece'),
      Ingredient(name: 'smoked salmon', quantity: '100 g'),
      Ingredient(name: 'cottage cheese', quantity: '120 g'),
      Ingredient(name: 'cucumber', quantity: ''),
      Ingredient(name: 'lemon', quantity: ''),
      Ingredient(name: 'dill', quantity: ''),
      Ingredient(name: 'black pepper', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Protein-Rich French Yogurt Parfait',
    calories: 390,
    protein: 31,
    carbs: 42,
    fat: 10,
    portions: 1,
    mealType: MealType.breakfast,
    photoPath: 'assets/images/community_thumbnails/protein_rich_french_yogurt_parfait.jpg',
    description: 'Layer skyr, berries, oats and almonds. Repeat layers. Finish with berries and honey.',
    ingredients: [
      Ingredient(name: 'skyr', quantity: '250 g'),
      Ingredient(name: 'berries', quantity: '100 g'),
      Ingredient(name: 'oats', quantity: '25 g'),
      Ingredient(name: 'almonds', quantity: '15 g'),
      Ingredient(name: 'honey', quantity: '1 tsp'),
      Ingredient(name: 'vanilla', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Chicken & Vegetable Breakfast Frittata',
    calories: 470,
    protein: 50,
    carbs: 15,
    fat: 21,
    portions: 1,
    mealType: MealType.breakfast,
    photoPath: 'assets/images/community_thumbnails/chicken_vegetable_breakfast_frittata.jpg',
    description: 'Sauté vegetables. Add diced chicken. Pour over beaten eggs and egg whites. Add cheese. Cook gently and finish under grill until golden.',
    ingredients: [
      Ingredient(name: 'eggs', quantity: '2 piece'),
      Ingredient(name: 'egg whites', quantity: '120 g'),
      Ingredient(name: 'cooked chicken breast', quantity: '100 g'),
      Ingredient(name: 'zucchini', quantity: '100 g'),
      Ingredient(name: 'red pepper', quantity: '50 g'),
      Ingredient(name: 'cheese', quantity: '30 g'),
      Ingredient(name: 'olive oil', quantity: '1 tsp'),
      Ingredient(name: 'herbs', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Salade Niçoise with Tuna & Eggs',
    calories: 600,
    protein: 55,
    carbs: 45,
    fat: 24,
    portions: 1,
    mealType: MealType.lunch,
    photoPath: 'assets/images/community_thumbnails/salade_nicoise_with_tuna_eggs.jpg',
    description: 'Boil potatoes and green beans. Boil eggs. Arrange lettuce, tomatoes, beans, potatoes, tuna, eggs and olives. Dress with olive oil, lemon and mustard.',
    ingredients: [
      Ingredient(name: 'tuna in water', quantity: '150 g'),
      Ingredient(name: 'eggs', quantity: '2 piece'),
      Ingredient(name: 'potatoes', quantity: '150 g'),
      Ingredient(name: 'green beans', quantity: '100 g'),
      Ingredient(name: 'tomatoes', quantity: '100 g'),
      Ingredient(name: 'lettuce', quantity: ''),
      Ingredient(name: 'olives', quantity: '30 g'),
      Ingredient(name: 'olive oil', quantity: '1 tsp'),
      Ingredient(name: 'lemon', quantity: ''),
      Ingredient(name: 'dijon mustard', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Chicken Ratatouille Bowl',
    calories: 560,
    protein: 58,
    carbs: 45,
    fat: 17,
    portions: 1,
    mealType: MealType.lunch,
    photoPath: 'assets/images/community_thumbnails/chicken_ratatouille_bowl.jpg',
    description: 'Brown chicken. Cook onion, zucchini and eggplant. Add tomatoes and garlic. Simmer 15–20 minutes. Add cooked lentils. Serve sliced chicken on top.',
    ingredients: [
      Ingredient(name: 'chicken breast', quantity: '180 g'),
      Ingredient(name: 'zucchini', quantity: '150 g'),
      Ingredient(name: 'eggplant', quantity: '100 g'),
      Ingredient(name: 'tomatoes', quantity: '120 g'),
      Ingredient(name: 'onion', quantity: '50 g'),
      Ingredient(name: 'cooked lentils', quantity: '100 g'),
      Ingredient(name: 'olive oil', quantity: '1 tsp'),
      Ingredient(name: 'garlic', quantity: ''),
      Ingredient(name: 'herbes de provence', quantity: ''),
    ],
  ),
  Recipe(
    name: 'High-Protein Quiche Lorraine with Turkey',
    calories: 500,
    protein: 43,
    carbs: 35,
    fat: 22,
    portions: 1,
    mealType: MealType.lunch,
    photoPath: 'assets/images/community_thumbnails/high_protein_quiche_lorraine_with_turkey.jpg',
    description: 'Place pastry in tart tin. Add chopped turkey. Whisk eggs, egg whites, milk and cottage cheese. Pour over turkey. Add Gruyère. Bake at 180°C for 35–40 minutes.',
    ingredients: [
      Ingredient(name: 'whole-grain pie crust', quantity: '1 piece'),
      Ingredient(name: 'eggs', quantity: '4 piece'),
      Ingredient(name: 'egg whites', quantity: '200 g'),
      Ingredient(name: 'turkey breast', quantity: '120 g'),
      Ingredient(name: 'cottage cheese', quantity: '80 g'),
      Ingredient(name: 'gruyère', quantity: '50 g'),
      Ingredient(name: 'milk', quantity: '100 ml'),
      Ingredient(name: 'nutmeg', quantity: ''),
      Ingredient(name: 'pepper', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Blanquette-Style Chicken with Mushrooms',
    calories: 520,
    protein: 60,
    carbs: 30,
    fat: 16,
    portions: 1,
    mealType: MealType.lunch,
    photoPath: 'assets/images/community_thumbnails/blanquette_style_chicken_with_mushrooms.jpg',
    description: 'Cook chicken and vegetables gently. Make light sauce with flour and milk. Add mushrooms. Remove from heat and stir in Greek yogurt. Finish with lemon and parsley.',
    ingredients: [
      Ingredient(name: 'chicken breast', quantity: '200 g'),
      Ingredient(name: 'mushrooms', quantity: '150 g'),
      Ingredient(name: 'carrots', quantity: '100 g'),
      Ingredient(name: 'onion', quantity: '80 g'),
      Ingredient(name: 'low-fat milk', quantity: '150 ml'),
      Ingredient(name: 'greek yogurt', quantity: '80 g'),
      Ingredient(name: 'flour', quantity: '10 g'),
      Ingredient(name: 'lemon', quantity: ''),
      Ingredient(name: 'parsley', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Tuna Pan Bagnat',
    calories: 590,
    protein: 50,
    carbs: 58,
    fat: 19,
    portions: 1,
    mealType: MealType.lunch,
    photoPath: 'assets/images/community_thumbnails/tuna_pan_bagnat.jpg',
    description: 'Mix tuna with lemon and olive oil. Fill bread with tuna, egg, tomato, cucumber, lettuce and olives. Press firmly before serving.',
    ingredients: [
      Ingredient(name: 'whole-grain round bread', quantity: '1 piece'),
      Ingredient(name: 'tuna', quantity: '150 g'),
      Ingredient(name: 'egg', quantity: '1 piece'),
      Ingredient(name: 'tomato', quantity: ''),
      Ingredient(name: 'cucumber', quantity: ''),
      Ingredient(name: 'lettuce', quantity: ''),
      Ingredient(name: 'olives', quantity: '20 g'),
      Ingredient(name: 'olive oil', quantity: '1 tsp'),
      Ingredient(name: 'lemon', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Turkey Croque-Monsieur with Side Salad',
    calories: 560,
    protein: 48,
    carbs: 48,
    fat: 22,
    portions: 1,
    mealType: MealType.lunch,
    photoPath: 'assets/images/community_thumbnails/turkey_croque_monsieur_with_side_salad.jpg',
    description: 'Build sandwich with mustard, turkey and cheese. Cover with béchamel and extra cheese. Bake until golden. Serve with dressed salad.',
    ingredients: [
      Ingredient(name: 'slices whole-grain bread', quantity: '2 piece'),
      Ingredient(name: 'turkey', quantity: '120 g'),
      Ingredient(name: 'gruyère', quantity: '40 g'),
      Ingredient(name: 'light béchamel', quantity: '60 ml'),
      Ingredient(name: 'green salad', quantity: ''),
      Ingredient(name: 'tomato', quantity: ''),
      Ingredient(name: 'dijon mustard', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Lentil & Salmon French Bistro Salad',
    calories: 570,
    protein: 47,
    carbs: 43,
    fat: 24,
    portions: 1,
    mealType: MealType.lunch,
    photoPath: 'assets/images/community_thumbnails/lentil_salmon_french_bistro_salad.jpg',
    description: 'Cook salmon and let cool slightly. Combine lentils and vegetables. Make yogurt-Dijon dressing. Add salmon and herbs.',
    ingredients: [
      Ingredient(name: 'cooked green lentils', quantity: '150 g'),
      Ingredient(name: 'cooked salmon', quantity: '150 g'),
      Ingredient(name: 'carrot', quantity: '100 g'),
      Ingredient(name: 'cucumber', quantity: '50 g'),
      Ingredient(name: 'mixed greens', quantity: ''),
      Ingredient(name: 'greek yogurt', quantity: '50 g'),
      Ingredient(name: 'dijon mustard', quantity: ''),
      Ingredient(name: 'lemon', quantity: ''),
      Ingredient(name: 'dill', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Beef Bourguignon — Alcohol-Free',
    calories: 650,
    protein: 50,
    carbs: 52,
    fat: 25,
    portions: 1,
    mealType: MealType.lunch,
    photoPath: 'assets/images/community_thumbnails/beef_bourguignon_alcohol_free.jpg',
    description: 'Brown beef well. Add onion and carrot. Add tomato and stock. Add mushrooms, garlic, thyme and bay. Simmer 1½–2 hours. Serve with boiled potatoes.',
    ingredients: [
      Ingredient(name: 'lean beef', quantity: '180 g'),
      Ingredient(name: 'mushrooms', quantity: '150 g'),
      Ingredient(name: 'carrots', quantity: '100 g'),
      Ingredient(name: 'onion', quantity: '100 g'),
      Ingredient(name: 'beef stock', quantity: '150 ml'),
      Ingredient(name: 'tomato passata', quantity: '100 g'),
      Ingredient(name: 'potatoes', quantity: '150 g'),
      Ingredient(name: 'garlic', quantity: ''),
      Ingredient(name: 'thyme', quantity: ''),
      Ingredient(name: 'bay leaf', quantity: ''),
    ],
  ),
  Recipe(
    name: 'High-Protein Hachis Parmentier',
    calories: 580,
    protein: 49,
    carbs: 48,
    fat: 23,
    portions: 1,
    mealType: MealType.lunch,
    photoPath: 'assets/images/community_thumbnails/high_protein_hachis_parmentier.jpg',
    description: 'Cook beef with onion and carrot. Boil potato and cauliflower. Mash with Greek yogurt. Layer beef and mash in baking dish. Add cheese. Bake until golden.',
    ingredients: [
      Ingredient(name: 'lean minced beef', quantity: '180 g'),
      Ingredient(name: 'potato', quantity: '150 g'),
      Ingredient(name: 'cauliflower', quantity: '100 g'),
      Ingredient(name: 'carrot', quantity: '80 g'),
      Ingredient(name: 'onion', quantity: '50 g'),
      Ingredient(name: 'greek yogurt', quantity: '50 g'),
      Ingredient(name: 'grated cheese', quantity: '25 g'),
      Ingredient(name: 'garlic', quantity: ''),
      Ingredient(name: 'thyme', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Bouillabaisse-Style High-Protein Fish Stew',
    calories: 520,
    protein: 58,
    carbs: 38,
    fat: 12,
    portions: 1,
    mealType: MealType.lunch,
    photoPath: 'assets/images/community_thumbnails/bouillabaisse_style_high_protein_fish_stew.jpg',
    description: 'Cook onion, fennel and garlic. Add tomatoes, stock and saffron. Add potatoes and simmer. Add cod, prawns and mussels near the end. Cook until seafood is just done.',
    ingredients: [
      Ingredient(name: 'cod', quantity: '120 g'),
      Ingredient(name: 'prawns', quantity: '100 g'),
      Ingredient(name: 'mussels', quantity: '100 g'),
      Ingredient(name: 'tomatoes', quantity: '150 g'),
      Ingredient(name: 'fennel', quantity: '100 g'),
      Ingredient(name: 'potato', quantity: '80 g'),
      Ingredient(name: 'onion', quantity: ''),
      Ingredient(name: 'garlic', quantity: ''),
      Ingredient(name: 'saffron', quantity: ''),
      Ingredient(name: 'fish stock', quantity: ''),
      Ingredient(name: 'parsley', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Chicken Coq-au-Vin Style — No Alcohol',
    calories: 600,
    protein: 55,
    carbs: 38,
    fat: 24,
    portions: 1,
    mealType: MealType.dinner,
    photoPath: 'assets/images/community_thumbnails/chicken_coq_au_vin_style_no_alcohol.jpg',
    description: 'Brown chicken. Add vegetables and tomato paste. Add stock and diluted grape juice. Add herbs. Simmer 35–45 minutes until tender.',
    ingredients: [
      Ingredient(name: 'chicken thighs, skinless', quantity: '220 g'),
      Ingredient(name: 'mushrooms', quantity: '150 g'),
      Ingredient(name: 'carrots', quantity: '100 g'),
      Ingredient(name: 'onion', quantity: '100 g'),
      Ingredient(name: 'chicken stock', quantity: '200 ml'),
      Ingredient(name: 'grape juice', quantity: '100 ml'),
      Ingredient(name: 'water', quantity: '100 ml'),
      Ingredient(name: 'tomato paste', quantity: ''),
      Ingredient(name: 'thyme', quantity: ''),
      Ingredient(name: 'bay leaf', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Lean Beef Bourguignon with Cauliflower Mash',
    calories: 590,
    protein: 58,
    carbs: 25,
    fat: 27,
    portions: 1,
    mealType: MealType.dinner,
    photoPath: 'assets/images/community_thumbnails/lean_beef_bourguignon_with_cauliflower_mash.jpg',
    description: 'Cook beef slowly with vegetables, stock and herbs until tender. Steam cauliflower. Mash cauliflower with Greek yogurt. Serve beef over mash.',
    ingredients: [
      Ingredient(name: 'lean beef', quantity: '200 g'),
      Ingredient(name: 'mushrooms', quantity: '200 g'),
      Ingredient(name: 'carrot', quantity: ''),
      Ingredient(name: 'onion', quantity: ''),
      Ingredient(name: 'beef stock', quantity: ''),
      Ingredient(name: 'tomato paste', quantity: ''),
      Ingredient(name: 'thyme', quantity: ''),
      Ingredient(name: 'cauliflower', quantity: '250 g'),
      Ingredient(name: 'greek yogurt', quantity: '50 g'),
    ],
  ),
  Recipe(
    name: 'Chicken Chasseur',
    calories: 610,
    protein: 62,
    carbs: 47,
    fat: 18,
    portions: 1,
    mealType: MealType.dinner,
    photoPath: 'assets/images/community_thumbnails/chicken_chasseur.jpg',
    description: 'Brown chicken. Sauté onion and mushrooms. Add tomatoes and stock. Return chicken and simmer until cooked. Serve with potatoes.',
    ingredients: [
      Ingredient(name: 'chicken breast', quantity: '220 g'),
      Ingredient(name: 'mushrooms', quantity: '150 g'),
      Ingredient(name: 'tomatoes', quantity: '150 g'),
      Ingredient(name: 'onion', quantity: '100 g'),
      Ingredient(name: 'potatoes', quantity: '150 g'),
      Ingredient(name: 'chicken stock', quantity: ''),
      Ingredient(name: 'garlic', quantity: ''),
      Ingredient(name: 'parsley', quantity: ''),
      Ingredient(name: 'thyme', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Turkey Ratatouille with Herbed Potatoes',
    calories: 580,
    protein: 58,
    carbs: 55,
    fat: 15,
    portions: 1,
    mealType: MealType.dinner,
    photoPath: 'assets/images/community_thumbnails/turkey_ratatouille_with_herbed_potatoes.jpg',
    description: 'Cook ratatouille slowly. Roast potatoes with herbs. Grill or pan-cook turkey. Slice and serve over vegetables.',
    ingredients: [
      Ingredient(name: 'turkey breast', quantity: '220 g'),
      Ingredient(name: 'ratatouille vegetables', quantity: '250 g'),
      Ingredient(name: 'potatoes', quantity: '180 g'),
      Ingredient(name: 'olive oil', quantity: '1 tsp'),
      Ingredient(name: 'garlic', quantity: ''),
      Ingredient(name: 'basil', quantity: ''),
      Ingredient(name: 'herbes de provence', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Salmon Gratin Dauphinois-Style',
    calories: 680,
    protein: 47,
    carbs: 45,
    fat: 34,
    portions: 1,
    mealType: MealType.dinner,
    photoPath: 'assets/images/community_thumbnails/salmon_gratin_dauphinois_style.jpg',
    description: 'Slice potatoes thinly. Layer with spinach. Mix milk and yogurt with garlic and nutmeg. Add salmon and cheese. Bake at 180°C until potatoes are tender.',
    ingredients: [
      Ingredient(name: 'salmon', quantity: '180 g'),
      Ingredient(name: 'potatoes', quantity: '200 g'),
      Ingredient(name: 'spinach', quantity: '100 g'),
      Ingredient(name: 'milk', quantity: '100 ml'),
      Ingredient(name: 'greek yogurt', quantity: '50 g'),
      Ingredient(name: 'gruyère', quantity: '30 g'),
      Ingredient(name: 'garlic', quantity: ''),
      Ingredient(name: 'nutmeg', quantity: ''),
    ],
  ),
  Recipe(
    name: 'High-Protein Tartiflette with Chicken',
    calories: 690,
    protein: 54,
    carbs: 55,
    fat: 31,
    portions: 1,
    mealType: MealType.dinner,
    photoPath: 'assets/images/community_thumbnails/high_protein_tartiflette_with_chicken.jpg',
    description: 'Cook potatoes. Sauté onion and mushrooms. Add chicken. Layer potatoes, chicken and vegetables. Add yogurt seasoning. Top with Reblochon and bake until bubbling.',
    ingredients: [
      Ingredient(name: 'chicken breast', quantity: '180 g'),
      Ingredient(name: 'potatoes', quantity: '250 g'),
      Ingredient(name: 'reblochon', quantity: '80 g'),
      Ingredient(name: 'onion', quantity: '100 g'),
      Ingredient(name: 'mushrooms', quantity: '100 g'),
      Ingredient(name: 'greek yogurt', quantity: '50 g'),
      Ingredient(name: 'black pepper', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Chicken Cassoulet-Style',
    calories: 650,
    protein: 57,
    carbs: 57,
    fat: 22,
    portions: 1,
    mealType: MealType.dinner,
    photoPath: 'assets/images/community_thumbnails/chicken_cassoulet_style.jpg',
    description: 'Brown chicken. Cook onion and carrot. Add beans, tomato and stock. Add herbs and chicken. Simmer 30–40 minutes. Finish under grill for a browned top.',
    ingredients: [
      Ingredient(name: 'chicken thigh', quantity: '180 g'),
      Ingredient(name: 'white beans', quantity: '180 g'),
      Ingredient(name: 'carrot', quantity: '100 g'),
      Ingredient(name: 'tomato', quantity: '100 g'),
      Ingredient(name: 'onion', quantity: ''),
      Ingredient(name: 'garlic', quantity: ''),
      Ingredient(name: 'thyme', quantity: ''),
      Ingredient(name: 'bay leaf', quantity: ''),
      Ingredient(name: 'chicken stock', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Steak au Poivre with Green Beans',
    calories: 650,
    protein: 57,
    carbs: 43,
    fat: 30,
    portions: 1,
    mealType: MealType.dinner,
    photoPath: 'assets/images/community_thumbnails/steak_au_poivre_with_green_beans.jpg',
    description: 'Season steak with pepper. Sear and rest. Make light mustard-yogurt sauce. Serve with potatoes and green beans.',
    ingredients: [
      Ingredient(name: 'lean beef steak', quantity: '200 g'),
      Ingredient(name: 'green beans', quantity: '200 g'),
      Ingredient(name: 'potatoes', quantity: '180 g'),
      Ingredient(name: 'greek yogurt', quantity: '60 g'),
      Ingredient(name: 'crushed black pepper', quantity: ''),
      Ingredient(name: 'dijon mustard', quantity: ''),
      Ingredient(name: 'garlic', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Turkey Meatballs à la Provençale',
    calories: 670,
    protein: 62,
    carbs: 64,
    fat: 18,
    portions: 1,
    mealType: MealType.dinner,
    photoPath: 'assets/images/community_thumbnails/turkey_meatballs_a_la_provencale.jpg',
    description: 'Mix turkey, egg, oats and herbs. Form meatballs and brown. Add tomato sauce and zucchini. Simmer 15 minutes. Serve over pasta.',
    ingredients: [
      Ingredient(name: 'lean turkey mince', quantity: '220 g'),
      Ingredient(name: 'egg', quantity: '1 piece'),
      Ingredient(name: 'oats', quantity: '20 g'),
      Ingredient(name: 'tomato passata', quantity: '200 g'),
      Ingredient(name: 'zucchini', quantity: '100 g'),
      Ingredient(name: 'garlic', quantity: ''),
      Ingredient(name: 'basil', quantity: ''),
      Ingredient(name: 'herbes de provence', quantity: ''),
      Ingredient(name: 'cooked whole-grain pasta', quantity: '150 g'),
    ],
  ),
  Recipe(
    name: 'Garlic-Herb Cod with French Lentils',
    calories: 550,
    protein: 61,
    carbs: 43,
    fat: 14,
    portions: 1,
    mealType: MealType.dinner,
    photoPath: 'assets/images/community_thumbnails/garlic_herb_cod_with_french_lentils.jpg',
    description: 'Cook lentils with carrots and leeks. Season cod with garlic, lemon and parsley. Bake at 200°C for 12–15 minutes. Serve cod over lentils.',
    ingredients: [
      Ingredient(name: 'cod', quantity: '220 g'),
      Ingredient(name: 'cooked green lentils', quantity: '180 g'),
      Ingredient(name: 'carrots', quantity: '100 g'),
      Ingredient(name: 'leeks', quantity: '100 g'),
      Ingredient(name: 'olive oil', quantity: '1 tsp'),
      Ingredient(name: 'garlic', quantity: ''),
      Ingredient(name: 'parsley', quantity: ''),
      Ingredient(name: 'lemon', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Skyr with Strawberries',
    calories: 210,
    protein: 24,
    portions: 1,
    mealType: MealType.snack,
    photoPath: 'assets/images/community_thumbnails/skyr_with_strawberries.jpg',
    description: 'Combine all ingredients in a bowl.',
    ingredients: [
      Ingredient(name: 'skyr', quantity: '200 g'),
      Ingredient(name: 'strawberries', quantity: '100 g'),
      Ingredient(name: 'almonds', quantity: '10 g'),
      Ingredient(name: 'cinnamon', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Cottage Cheese & Apple',
    calories: 300,
    protein: 25,
    portions: 1,
    mealType: MealType.snack,
    photoPath: 'assets/images/community_thumbnails/cottage_cheese_apple.jpg',
    description: 'Dice apple and combine with cottage cheese, cinnamon and walnuts.',
    ingredients: [
      Ingredient(name: 'cottage cheese', quantity: '200 g'),
      Ingredient(name: 'small apple', quantity: '1 piece'),
      Ingredient(name: 'cinnamon', quantity: ''),
      Ingredient(name: 'walnuts', quantity: '10 g'),
    ],
  ),
  Recipe(
    name: 'Tuna Cucumber Bites',
    calories: 190,
    protein: 28,
    portions: 1,
    mealType: MealType.snack,
    photoPath: 'assets/images/community_thumbnails/tuna_cucumber_bites.jpg',
    description: 'Mix tuna with yogurt and mustard. Spoon onto cucumber slices.',
    ingredients: [
      Ingredient(name: 'tuna', quantity: '100 g'),
      Ingredient(name: 'greek yogurt', quantity: '60 g'),
      Ingredient(name: 'cucumber', quantity: ''),
      Ingredient(name: 'dijon mustard', quantity: ''),
      Ingredient(name: 'lemon', quantity: ''),
      Ingredient(name: 'dill', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Boiled Eggs & Crudités',
    calories: 280,
    protein: 20,
    portions: 1,
    mealType: MealType.snack,
    photoPath: 'assets/images/community_thumbnails/boiled_eggs_crudites.jpg',
    description: 'Boil eggs 9–10 minutes. Cut vegetables. Mix yogurt and Dijon as dip.',
    ingredients: [
      Ingredient(name: 'eggs', quantity: '2 piece'),
      Ingredient(name: 'carrot', quantity: ''),
      Ingredient(name: 'cucumber', quantity: ''),
      Ingredient(name: 'cherry tomatoes', quantity: ''),
      Ingredient(name: 'greek yogurt', quantity: '40 g'),
      Ingredient(name: 'dijon mustard', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Mini Turkey & Gruyère Roll-Ups',
    calories: 240,
    protein: 29,
    portions: 1,
    mealType: MealType.snack,
    photoPath: 'assets/images/community_thumbnails/mini_turkey_gruyere_roll_ups.jpg',
    description: 'Spread mustard. Add cheese and cucumber. Roll tightly and slice.',
    ingredients: [
      Ingredient(name: 'turkey slices', quantity: '100 g'),
      Ingredient(name: 'gruyère', quantity: '40 g'),
      Ingredient(name: 'cucumber', quantity: ''),
      Ingredient(name: 'mustard', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Skyr Chocolate Mousse',
    calories: 220,
    protein: 25,
    portions: 1,
    mealType: MealType.snack,
    photoPath: 'assets/images/community_thumbnails/skyr_chocolate_mousse.jpg',
    description: 'Whisk skyr, cocoa, vanilla and honey. Chill. Shave dark chocolate over top.',
    ingredients: [
      Ingredient(name: 'skyr', quantity: '200 g'),
      Ingredient(name: 'unsweetened cocoa', quantity: '10 g'),
      Ingredient(name: 'dark chocolate', quantity: '10 g'),
      Ingredient(name: 'vanilla', quantity: ''),
      Ingredient(name: 'honey', quantity: '1 tsp'),
    ],
  ),
  Recipe(
    name: 'Edamame & Lemon Snack Bowl',
    calories: 210,
    protein: 18,
    portions: 1,
    mealType: MealType.snack,
    photoPath: 'assets/images/community_thumbnails/edamame_lemon_snack_bowl.jpg',
    description: 'Steam edamame. Season with lemon, salt and chili.',
    ingredients: [
      Ingredient(name: 'edamame', quantity: '150 g'),
      Ingredient(name: 'lemon', quantity: ''),
      Ingredient(name: 'sea salt', quantity: ''),
      Ingredient(name: 'chili flakes', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Greek Yogurt & Blueberry Bowl',
    calories: 250,
    protein: 23,
    portions: 1,
    mealType: MealType.snack,
    photoPath: 'assets/images/community_thumbnails/greek_yogurt_blueberry_bowl.jpg',
    description: 'Mix or layer ingredients.',
    ingredients: [
      Ingredient(name: 'greek yogurt', quantity: '200 g'),
      Ingredient(name: 'blueberries', quantity: '100 g'),
      Ingredient(name: 'almonds', quantity: '15 g'),
      Ingredient(name: 'cinnamon', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Smoked Salmon Cucumber Rolls',
    calories: 220,
    protein: 27,
    portions: 1,
    mealType: MealType.snack,
    photoPath: 'assets/images/community_thumbnails/smoked_salmon_cucumber_rolls.jpg',
    description: 'Cut cucumber into long ribbons. Spread cottage cheese. Add salmon and roll.',
    ingredients: [
      Ingredient(name: 'smoked salmon', quantity: '80 g'),
      Ingredient(name: 'cottage cheese', quantity: '100 g'),
      Ingredient(name: 'cucumber', quantity: ''),
      Ingredient(name: 'lemon', quantity: ''),
      Ingredient(name: 'dill', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Cottage Cheese Chocolate Berry Cup',
    calories: 240,
    protein: 25,
    portions: 1,
    mealType: MealType.snack,
    photoPath: 'assets/images/community_thumbnails/cottage_cheese_chocolate_berry_cup.jpg',
    description: 'Blend cottage cheese with cocoa and vanilla. Top with raspberries and chocolate.',
    ingredients: [
      Ingredient(name: 'cottage cheese', quantity: '180 g'),
      Ingredient(name: 'raspberries', quantity: '80 g'),
      Ingredient(name: 'cocoa', quantity: '5 g'),
      Ingredient(name: 'dark chocolate', quantity: '10 g'),
      Ingredient(name: 'vanilla', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Strawberry Skyr Smoothie',
    calories: 250,
    protein: 25,
    portions: 1,
    mealType: MealType.drink,
    photoPath: 'assets/images/community_thumbnails/strawberry_skyr_smoothie.jpg',
    description: 'Blend everything until smooth.',
    ingredients: [
      Ingredient(name: 'skyr', quantity: '150 g'),
      Ingredient(name: 'semi-skimmed milk', quantity: '200 ml'),
      Ingredient(name: 'strawberries', quantity: '150 g'),
      Ingredient(name: 'ice', quantity: ''),
      Ingredient(name: 'vanilla', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Café Latte with Extra Milk',
    calories: 160,
    protein: 12,
    portions: 1,
    mealType: MealType.drink,
    photoPath: 'assets/images/community_thumbnails/cafe_latte_with_extra_milk.jpg',
    description: 'Steam or heat milk. Combine with espresso. Dust with cinnamon.',
    ingredients: [
      Ingredient(name: 'semi-skimmed milk', quantity: '250 ml'),
      Ingredient(name: 'espresso', quantity: '100 ml'),
      Ingredient(name: 'cinnamon', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Vanilla Banana Skyr Shake',
    calories: 300,
    protein: 25,
    portions: 1,
    mealType: MealType.drink,
    photoPath: 'assets/images/community_thumbnails/vanilla_banana_skyr_shake.jpg',
    description: 'Blend until completely smooth.',
    ingredients: [
      Ingredient(name: 'skyr', quantity: '150 g'),
      Ingredient(name: 'milk', quantity: '200 ml'),
      Ingredient(name: 'small banana', quantity: '1 piece'),
      Ingredient(name: 'vanilla', quantity: ''),
      Ingredient(name: 'cinnamon', quantity: ''),
      Ingredient(name: 'ice', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Raspberry Yogurt Lassi',
    calories: 250,
    protein: 21,
    portions: 1,
    mealType: MealType.drink,
    photoPath: 'assets/images/community_thumbnails/raspberry_yogurt_lassi.jpg',
    description: 'Blend until smooth and slightly frothy.',
    ingredients: [
      Ingredient(name: 'greek yogurt', quantity: '200 g'),
      Ingredient(name: 'raspberries', quantity: '150 g'),
      Ingredient(name: 'water', quantity: '150 ml'),
      Ingredient(name: 'honey', quantity: '1 tsp'),
      Ingredient(name: 'lemon', quantity: ''),
      Ingredient(name: 'ice', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Chocolate Skyr Milkshake',
    calories: 300,
    protein: 25,
    portions: 1,
    mealType: MealType.drink,
    photoPath: 'assets/images/community_thumbnails/chocolate_skyr_milkshake.jpg',
    description: 'Blend until thick and smooth.',
    ingredients: [
      Ingredient(name: 'skyr', quantity: '150 g'),
      Ingredient(name: 'milk', quantity: '200 ml'),
      Ingredient(name: 'cocoa', quantity: '10 g'),
      Ingredient(name: 'small banana', quantity: '1 piece'),
      Ingredient(name: 'vanilla', quantity: ''),
      Ingredient(name: 'ice', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Apple-Cinnamon Yogurt Smoothie',
    calories: 270,
    protein: 23,
    portions: 1,
    mealType: MealType.drink,
    photoPath: 'assets/images/community_thumbnails/apple_cinnamon_yogurt_smoothie.jpg',
    description: 'Blend everything until smooth.',
    ingredients: [
      Ingredient(name: 'greek yogurt', quantity: '170 g'),
      Ingredient(name: 'milk', quantity: '200 ml'),
      Ingredient(name: 'small apple', quantity: '1 piece'),
      Ingredient(name: 'cinnamon', quantity: ''),
      Ingredient(name: 'ice', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Coffee-Banana Skyr Smoothie',
    calories: 280,
    protein: 24,
    portions: 1,
    mealType: MealType.drink,
    photoPath: 'assets/images/community_thumbnails/coffee_banana_skyr_smoothie.jpg',
    description: 'Blend all ingredients until smooth and cold.',
    ingredients: [
      Ingredient(name: 'skyr', quantity: '150 g'),
      Ingredient(name: 'milk', quantity: '150 ml'),
      Ingredient(name: 'cold espresso', quantity: '100 ml'),
      Ingredient(name: 'small banana', quantity: '1 piece'),
      Ingredient(name: 'ice', quantity: ''),
      Ingredient(name: 'cinnamon', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Blueberry Almond Yogurt Drink',
    calories: 330,
    protein: 24,
    portions: 1,
    mealType: MealType.drink,
    photoPath: 'assets/images/community_thumbnails/blueberry_almond_yogurt_drink.jpg',
    description: 'Blend until creamy.',
    ingredients: [
      Ingredient(name: 'greek yogurt', quantity: '200 g'),
      Ingredient(name: 'blueberries', quantity: '150 g'),
      Ingredient(name: 'milk', quantity: '100 ml'),
      Ingredient(name: 'almond butter', quantity: '10 g'),
      Ingredient(name: 'ice', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Peach Skyr Smoothie',
    calories: 250,
    protein: 24,
    portions: 1,
    mealType: MealType.drink,
    photoPath: 'assets/images/community_thumbnails/peach_skyr_smoothie.jpg',
    description: 'Blend until silky smooth.',
    ingredients: [
      Ingredient(name: 'skyr', quantity: '180 g'),
      Ingredient(name: 'peach', quantity: '150 g'),
      Ingredient(name: 'milk', quantity: '150 ml'),
      Ingredient(name: 'vanilla', quantity: ''),
      Ingredient(name: 'ice', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Hot Vanilla Milk & Skyr Drink',
    calories: 210,
    protein: 18,
    portions: 1,
    mealType: MealType.drink,
    photoPath: 'assets/images/community_thumbnails/hot_vanilla_milk_skyr_drink.jpg',
    description: 'Warm milk without boiling. Whisk skyr separately. Let milk cool slightly. Whisk in skyr, vanilla, cinnamon and honey. Serve warm.',
    ingredients: [
      Ingredient(name: 'semi-skimmed milk', quantity: '200 ml'),
      Ingredient(name: 'skyr', quantity: '100 g'),
      Ingredient(name: 'vanilla', quantity: ''),
      Ingredient(name: 'cinnamon', quantity: ''),
      Ingredient(name: 'honey', quantity: '1 tsp'),
    ],
  ),
];
