import '../entities/ingredient.dart';
import '../entities/meal_type.dart';
import '../entities/recipe.dart';

/// Community-contributed breakfast recipes shown in the Community tab.
/// Calories/protein/carbs/fat/fiber are left at 0/null here — the Community
/// tab computes them on load by running each ingredient through the same
/// food-matching + nutrition-calculation pipeline used when a user adds a
/// recipe by hand (see [computeNutrition]).
List<Recipe> communityBreakfastRecipes() => [
  Recipe(
    name: 'High-Protein Greek Yogurt Pancakes',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: '',
    ingredients: [
      Ingredient(name: 'oat raw', quantity: '40 g'),
      Ingredient(name: 'yogurt greek', quantity: '120 g'),
      Ingredient(name: 'egg raw', quantity: '2 piece'),
      Ingredient(name: 'vanilla pod', quantity: '0.5 tsp'),
      Ingredient(name: 'cinnamon', quantity: '0.5 tsp'),
      Ingredient(name: 'blueberry raw', quantity: '50 g'),
      Ingredient(name: 'honey', quantity: '1 tsp'),
    ],
  ),
  Recipe(
    name: 'Cottage Cheese Protein Pancakes',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: '',
    ingredients: [
      Ingredient(name: 'oat raw', quantity: '40 g'),
      Ingredient(name: 'fresh cream cheese petit-suisse type plain', quantity: '100 g'),
      Ingredient(name: 'egg raw', quantity: '1 piece'),
      Ingredient(name: 'sodium bicarbonate', quantity: '0.25 tsp'),
      Ingredient(name: 'honey', quantity: '0.5 tsp'),
      Ingredient(name: 'cinnamon', quantity: '0.25 tsp'),
      Ingredient(name: 'blueberry raw', quantity: '50 g'),
      Ingredient(name: 'yogurt greek', quantity: '30 g'),
    ],
  ),
  Recipe(
    name: 'Greek Yogurt Overnight Oats',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: '',
    ingredients: [
      Ingredient(name: 'oat raw', quantity: '50 g'),
      Ingredient(name: 'yogurt greek', quantity: '150 g'),
      Ingredient(name: 'milk semi-skimmed', quantity: '100 ml'),
      Ingredient(name: 'chia seed', quantity: '10 g'),
      Ingredient(name: 'banana flesh without skin raw', quantity: '60 g'),
      Ingredient(name: 'blueberry raw', quantity: '50 g'),
      Ingredient(name: 'cinnamon', quantity: '0.5 tsp'),
    ],
  ),
  Recipe(
    name: 'Cottage Cheese & Greek Yogurt Breakfast Bowl',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: '',
    ingredients: [
      Ingredient(name: 'fresh cream cheese petit-suisse type plain', quantity: '110 g'),
      Ingredient(name: 'yogurt greek', quantity: '90 g'),
      Ingredient(name: 'almond peeled', quantity: '14 g'),
      Ingredient(name: 'walnut kernel', quantity: '14 g'),
      Ingredient(name: 'chia seed', quantity: '6 g'),
      Ingredient(name: 'strawberry raw', quantity: '50 g'),
      Ingredient(name: 'cinnamon', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Cottage Cheese Egg Bake',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: '',
    ingredients: [
      Ingredient(name: 'egg raw', quantity: '2 piece'),
      Ingredient(name: 'fresh cream cheese petit-suisse type plain', quantity: '100 g'),
      Ingredient(name: 'spinach raw', quantity: '30 g'),
      Ingredient(name: 'tomato raw', quantity: '50 g'),
      Ingredient(name: 'Parmesan', quantity: '10 g'),
      Ingredient(name: 'bread multigrain', quantity: '40 g'),
      Ingredient(name: 'black pepper', quantity: ''),
      Ingredient(name: 'herbes de provence', quantity: ''),
    ],
  ),
  Recipe(
    name: 'High-Protein Egg White Oatmeal',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: '',
    ingredients: [
      Ingredient(name: 'oat raw', quantity: '40 g'),
      Ingredient(name: 'milk semi-skimmed', quantity: '150 ml'),
      Ingredient(name: 'egg white', quantity: '100 g'),
      Ingredient(name: 'vanilla pod', quantity: '0.5 tsp'),
      Ingredient(name: 'cinnamon', quantity: '0.5 tsp'),
      Ingredient(name: 'raspberry raw', quantity: '50 g'),
      Ingredient(name: 'peanut butter', quantity: '10 g'),
    ],
  ),
  Recipe(
    name: 'Greek Yogurt Scrambled Eggs',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: '',
    ingredients: [
      Ingredient(name: 'egg raw', quantity: '3 piece'),
      Ingredient(name: 'yogurt greek', quantity: '60 g'),
      Ingredient(name: 'spinach raw', quantity: '30 g'),
      Ingredient(name: 'tomato raw', quantity: '50 g'),
      Ingredient(name: 'bread multigrain', quantity: '40 g'),
      Ingredient(name: 'chive', quantity: '5 g'),
      Ingredient(name: 'black pepper', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Apple & Peanut Butter Protein Overnight Oats',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: '',
    ingredients: [
      Ingredient(name: 'oat raw', quantity: '40 g'),
      Ingredient(name: 'yogurt greek', quantity: '100 g'),
      Ingredient(name: 'milk semi-skimmed', quantity: '100 ml'),
      Ingredient(name: 'hemp seed', quantity: '10 g'),
      Ingredient(name: 'chia seed', quantity: '5 g'),
      Ingredient(name: 'peanut butter', quantity: '15 g'),
      Ingredient(name: 'apple flesh and skin raw', quantity: '75 g'),
      Ingredient(name: 'maple syrup', quantity: '1 tsp'),
      Ingredient(name: 'cinnamon', quantity: ''),
    ],
  ),
  Recipe(
    name: 'Protein Baked Cinnamon Oats',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: '',
    ingredients: [
      Ingredient(name: 'oat raw', quantity: '40 g'),
      Ingredient(name: 'yogurt greek', quantity: '100 g'),
      Ingredient(name: 'egg white', quantity: '100 g'),
      Ingredient(name: 'chia seed', quantity: '5 g'),
      Ingredient(name: 'hemp seed', quantity: '5 g'),
      Ingredient(name: 'cinnamon', quantity: '0.5 tsp'),
      Ingredient(name: 'sugar brown', quantity: '0.5 tsp'),
      Ingredient(name: 'yogurt greek', quantity: '30 g'),
      Ingredient(name: 'berries', quantity: '50 g'),
    ],
  ),
  Recipe(
    name: 'Cottage Cheese Overnight Oats',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: '',
    ingredients: [
      Ingredient(name: 'oat raw', quantity: '40 g'),
      Ingredient(name: 'fresh cream cheese petit-suisse type plain', quantity: '100 g'),
      Ingredient(name: 'milk semi-skimmed', quantity: '100 ml'),
      Ingredient(name: 'banana flesh without skin raw', quantity: '60 g'),
      Ingredient(name: 'chia seed', quantity: '10 g'),
      Ingredient(name: 'cinnamon', quantity: '0.5 tsp'),
      Ingredient(name: 'maple syrup', quantity: '1 tsp'),
      Ingredient(name: 'berries', quantity: '50 g'),
    ],
  ),
];
