import 'package:eating_app/features/recipes/domain/entities/ingredient.dart';
import 'package:eating_app/features/recipes/domain/entities/meal_type.dart';
import 'package:eating_app/features/recipes/domain/entities/recipe.dart';

/// Recipes added via the community dev tool
/// (flutter run -d linux -t tool/community_dev/main.dart).
/// Appended to automatically by that tool — hand-edit only to delete an
/// entry; use the tool itself to add new ones so nutrition stays computed
/// by the same pipeline as the rest of the app.
List<Recipe> devGeneratedCommunityRecipes() => [
  Recipe(
    name: 'Greek Yogurt Protein Bowl',
    calories: 294,
    protein: 3,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Mix yogurt and protein powder.\nTop with blueberries, chia seeds and almonds.\nDrizzle with honey and serve.',
    ingredients: [
      Ingredient(
        name: 'Greek yogurt 0-2%',
        quantity: '250 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'vanilla protein powder',
        quantity: '20 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'blueberries',
        quantity: '100 g',
        calories: 57.70,
        protein: 0.87,
        carbs: 10.60,
        fat: 0.33,
        fiber: 2.40,
      ),
      Ingredient(
        name: 'chia seeds',
        quantity: '15 g',
        calories: 68.10,
        protein: 2.48,
        carbs: 1.16,
        fat: 4.60,
        fiber: 5.16,
      ),
      Ingredient(
        name: 'almonds',
        quantity: '15 g',
        calories: 135.00,
        protein: 0.00,
        carbs: 0.00,
        fat: 15.00,
        fiber: 0.00,
      ),
      Ingredient(
        name: 'honey',
        quantity: '10 g',
        calories: 33.10,
        protein: 0.07,
        carbs: 8.21,
        fat: 0.00,
        fiber: 0.00,
      ),
    ],
  ),
  Recipe(
    name: 'Spinach Feta Omelet',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Heat oil in a nonstick pan and wilt spinach.\nBeat eggs, pour into pan and cook until nearly set.\nAdd feta, fold omelet and serve with toast.',
    ingredients: [
      Ingredient(
        name: 'large eggs',
        quantity: '3 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'spinach',
        quantity: '60 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'feta cheese',
        quantity: '30 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'olive oil',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'slice whole-grain toast',
        quantity: '1 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Protein Banana Peanut Butter Oats',
    calories: 289,
    protein: 12,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Cook oats with milk until creamy.\nRemove from heat and stir in protein powder.\nTop with sliced banana, peanut butter and cinnamon.',
    ingredients: [
      Ingredient(
        name: 'rolled oats',
        quantity: '50 g',
        calories: 189.00,
        protein: 8.45,
        carbs: 27.85,
        fat: 3.45,
        fiber: 5.30,
      ),
      Ingredient(
        name: 'skim milk',
        quantity: '200 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'small banana',
        quantity: '1 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'whey protein',
        quantity: '20 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'peanut butter',
        quantity: '15 g',
        calories: 96.45,
        protein: 3.33,
        carbs: 2.60,
        fat: 7.71,
        fiber: 0.75,
      ),
      Ingredient(
        name: 'cinnamon',
        quantity: '0.5 tsp',
        calories: 3.35,
        protein: 0.06,
        carbs: 0.38,
        fat: 0.02,
        fiber: 0.73,
      ),
    ],
  ),
  Recipe(
    name: 'Cottage Cheese Berry Bowl',
    calories: 204,
    protein: 2,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Add cottage cheese to a bowl.\nTop with berries, walnuts and chia seeds.\nDrizzle with honey.',
    ingredients: [
      Ingredient(
        name: 'low-fat cottage cheese',
        quantity: '250 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'mixed berries',
        quantity: '100 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'walnuts',
        quantity: '15 g',
        calories: 135.00,
        protein: 0.00,
        carbs: 0.00,
        fat: 15.00,
        fiber: 0.00,
      ),
      Ingredient(
        name: 'chia seeds',
        quantity: '10 g',
        calories: 45.40,
        protein: 1.65,
        carbs: 0.77,
        fat: 3.07,
        fiber: 3.44,
      ),
      Ingredient(
        name: 'honey',
        quantity: '1 tsp',
        calories: 23.17,
        protein: 0.05,
        carbs: 5.75,
        fat: 0.00,
        fiber: 0.00,
      ),
    ],
  ),
  Recipe(
    name: 'Smoked Salmon Avocado Eggs',
    calories: 450,
    protein: 4,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Cook eggs to preference.\nToast bread and top with avocado and lemon juice.\nServe with eggs, smoked salmon and tomato.',
    ingredients: [
      Ingredient(
        name: 'large eggs',
        quantity: '2 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'smoked salmon',
        quantity: '70 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'avocado',
        quantity: '50 g',
        calories: 450.00,
        protein: 0.00,
        carbs: 0.00,
        fat: 50.00,
        fiber: 0.00,
      ),
      Ingredient(
        name: 'slice whole-grain toast',
        quantity: '1 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'tomato',
        quantity: '30 g',
        calories: null,
        protein: 4.23,
        carbs: 13.05,
        fat: 0.89,
        fiber: 3.69,
      ),
      Ingredient(
        name: 'lemon juice',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Chicken Egg Breakfast Wrap',
    calories: 21,
    protein: 1,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Scramble eggs with pepper and spinach.\nAdd chicken and warm through.\nFill tortilla, add yogurt and roll tightly.',
    ingredients: [
      Ingredient(
        name: 'whole-grain tortilla (60 g)',
        quantity: '1 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cooked chicken breast',
        quantity: '80 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'large eggs',
        quantity: '2 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'bell pepper',
        quantity: '40 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'spinach',
        quantity: '30 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'Greek yogurt',
        quantity: '20 g',
        calories: 20.60,
        protein: 0.60,
        carbs: 0.75,
        fat: 1.63,
        fiber: 0.01,
      ),
    ],
  ),
  Recipe(
    name: 'Protein Berry Pancakes',
    calories: 103,
    protein: 3,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Whisk oat flour, egg, yogurt, protein powder, milk and baking powder.\nCook small pancakes on a lightly greased nonstick pan.\nServe with berries and remaining yogurt.',
    ingredients: [
      Ingredient(
        name: 'oat flour',
        quantity: '50 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'egg',
        quantity: '1 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'Greek yogurt',
        quantity: '100 g',
        calories: 103.00,
        protein: 3.02,
        carbs: 3.73,
        fat: 8.16,
        fiber: 0.07,
      ),
      Ingredient(
        name: 'whey protein',
        quantity: '20 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'milk',
        quantity: '60 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'berries',
        quantity: '80 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'baking powder',
        quantity: '0.5 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Shakshuka with Whole-Grain Toast',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Saute onion and pepper in oil.\nAdd tomatoes and cumin and simmer 8-10 minutes.\nMake two wells, add eggs, cover and cook until whites set.\nServe with toast.',
    ingredients: [
      Ingredient(
        name: 'large eggs',
        quantity: '2 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'chopped tomatoes',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'bell pepper',
        quantity: '50 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'onion',
        quantity: '40 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'olive oil',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cumin',
        quantity: '0.5 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'slice whole-grain toast',
        quantity: '1 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Blueberry Overnight Protein Oats',
    calories: 466,
    protein: 16,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Combine all ingredients in a sealed jar.\nStir well, cover and refrigerate at least 4 hours or overnight.\nServe cold.',
    ingredients: [
      Ingredient(
        name: 'rolled oats',
        quantity: '50 g',
        calories: 189.00,
        protein: 8.45,
        carbs: 27.85,
        fat: 3.45,
        fiber: 5.30,
      ),
      Ingredient(
        name: 'Greek yogurt',
        quantity: '180 g',
        calories: 185.40,
        protein: 5.44,
        carbs: 6.71,
        fat: 14.69,
        fiber: 0.13,
      ),
      Ingredient(
        name: 'skim milk',
        quantity: '100 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'whey protein',
        quantity: '20 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'blueberries',
        quantity: '80 g',
        calories: 46.16,
        protein: 0.70,
        carbs: 8.48,
        fat: 0.26,
        fiber: 1.92,
      ),
      Ingredient(
        name: 'chia seeds',
        quantity: '10 g',
        calories: 45.40,
        protein: 1.65,
        carbs: 0.77,
        fat: 3.07,
        fiber: 3.44,
      ),
    ],
  ),
  Recipe(
    name: 'Turkey Avocado Egg Toast',
    calories: 450,
    protein: 4,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Toast bread.\nCook eggs to preference.\nLayer avocado, turkey, tomato and eggs on toast.',
    ingredients: [
      Ingredient(
        name: 'slices whole-grain bread',
        quantity: '2 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'large eggs',
        quantity: '2 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'sliced roasted turkey breast',
        quantity: '60 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'avocado',
        quantity: '50 g',
        calories: 450.00,
        protein: 0.00,
        carbs: 0.00,
        fat: 50.00,
        fiber: 0.00,
      ),
      Ingredient(
        name: 'tomato',
        quantity: '30 g',
        calories: null,
        protein: 4.23,
        carbs: 13.05,
        fat: 0.89,
        fiber: 3.69,
      ),
    ],
  ),
  Recipe(
    name: 'Grilled Chicken Quinoa Bowl',
    calories: 31,
    protein: 1,
    portions: 1,
    mealType: MealType.lunch,
    description: 'Season and grill chicken, then slice.\nCombine quinoa and roasted vegetables.\nTop with chicken and yogurt mixed with lemon juice.',
    ingredients: [
      Ingredient(
        name: 'cooked chicken breast',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cooked quinoa',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'mixed roasted vegetables',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'olive oil',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'Greek yogurt',
        quantity: '30 g',
        calories: 30.90,
        protein: 0.91,
        carbs: 1.12,
        fat: 2.45,
        fiber: 0.02,
      ),
      Ingredient(
        name: 'lemon juice',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Tuna Chickpea Mediterranean Salad',
    calories: 14,
    protein: 15,
    portions: 1,
    mealType: MealType.lunch,
    description: 'Combine tuna, chickpeas and vegetables.\nAdd feta.\nDress with olive oil and lemon juice and toss.',
    ingredients: [
      Ingredient(
        name: 'canned tuna in water, drained',
        quantity: '120 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cooked chickpeas',
        quantity: '120 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cucumber',
        quantity: '100 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'tomato',
        quantity: '100 g',
        calories: null,
        protein: 14.10,
        carbs: 43.50,
        fat: 2.97,
        fiber: 12.30,
      ),
      Ingredient(
        name: 'red onion',
        quantity: '40 g',
        calories: 14.00,
        protein: 0.52,
        carbs: 2.25,
        fat: 0.16,
        fiber: 1.00,
      ),
      Ingredient(
        name: 'feta',
        quantity: '30 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'olive oil',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'lemon juice',
        quantity: '1 tbsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Chicken Shawarma Bowl',
    calories: 134,
    protein: 4,
    portions: 1,
    mealType: MealType.lunch,
    description: 'Season chicken with cumin and paprika and grill.\nAdd rice to a bowl.\nTop with chicken, salad, hummus and yogurt.',
    ingredients: [
      Ingredient(
        name: 'cooked chicken breast',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cooked brown rice',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cucumber-tomato salad',
        quantity: '100 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'hummus',
        quantity: '40 g',
        calories: 103.20,
        protein: 3.22,
        carbs: 3.60,
        fat: 7.96,
        fiber: 2.07,
      ),
      Ingredient(
        name: 'Greek yogurt',
        quantity: '30 g',
        calories: 30.90,
        protein: 0.91,
        carbs: 1.12,
        fat: 2.45,
        fiber: 0.02,
      ),
      Ingredient(
        name: 'cumin',
        quantity: '0.5 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'paprika',
        quantity: '0.5 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Turkey Avocado Whole-Grain Wrap',
    calories: 578,
    protein: 13,
    portions: 1,
    mealType: MealType.lunch,
    description: 'Spread yogurt and mustard on tortilla.\nAdd turkey, avocado and vegetables.\nRoll tightly and slice.',
    ingredients: [
      Ingredient(
        name: 'whole-grain tortilla (60 g)',
        quantity: '1 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'roasted turkey breast',
        quantity: '120 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'avocado',
        quantity: '60 g',
        calories: 540.00,
        protein: 0.00,
        carbs: 0.00,
        fat: 60.00,
        fiber: 0.00,
      ),
      Ingredient(
        name: 'lettuce',
        quantity: '50 g',
        calories: 7.35,
        protein: 0.68,
        carbs: 0.61,
        fat: 0.10,
        fiber: 0.55,
      ),
      Ingredient(
        name: 'tomato',
        quantity: '80 g',
        calories: null,
        protein: 11.28,
        carbs: 34.80,
        fat: 2.38,
        fiber: 9.84,
      ),
      Ingredient(
        name: 'Greek yogurt',
        quantity: '30 g',
        calories: 30.90,
        protein: 0.91,
        carbs: 1.12,
        fat: 2.45,
        fiber: 0.02,
      ),
      Ingredient(
        name: 'mustard',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Salmon Sweet Potato Broccoli Plate',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.lunch,
    description: 'Bake sweet potato until tender.\nBake salmon at 200 C until cooked through, about 12-15 minutes.\nSteam broccoli and finish with oil and lemon.\nServe together.',
    ingredients: [
      Ingredient(
        name: 'salmon fillet',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'sweet potato',
        quantity: '200 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'broccoli',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'olive oil',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'lemon juice',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Chicken Pesto Vegetable Pasta',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.lunch,
    description: 'Cook pasta and drain.\nSaute vegetables in oil.\nToss pasta with pesto and vegetables and top with sliced chicken.',
    ingredients: [
      Ingredient(
        name: 'cooked chicken breast',
        quantity: '140 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cooked whole-wheat pasta',
        quantity: '160 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'zucchini and cherry tomatoes',
        quantity: '120 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'pesto',
        quantity: '20 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'olive oil',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Beef Vegetable Stir-Fry',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.lunch,
    description: 'Heat oil in a wok or pan.\nStir-fry beef until browned, then add vegetables.\nAdd soy sauce and ginger and cook until vegetables are crisp-tender.\nServe over rice.',
    ingredients: [
      Ingredient(
        name: 'lean beef strips',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cooked brown rice',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'mixed broccoli, peppers and carrots',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'sesame oil',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
      Ingredient(
        name: 'low-sodium soy sauce',
        quantity: '1 tbsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'grated ginger',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Lentil Chicken Power Salad',
    calories: 0,
    protein: 14,
    portions: 1,
    mealType: MealType.lunch,
    description: 'Slice cooked chicken.\nCombine lentils and vegetables with spinach.\nTop with chicken and dress with oil and lemon.',
    ingredients: [
      Ingredient(
        name: 'cooked chicken breast',
        quantity: '120 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cooked lentils',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cucumber',
        quantity: '100 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'tomato',
        quantity: '100 g',
        calories: null,
        protein: 14.10,
        carbs: 43.50,
        fat: 2.97,
        fiber: 12.30,
      ),
      Ingredient(
        name: 'spinach',
        quantity: '50 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'olive oil',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'lemon juice',
        quantity: '1 tbsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Tuna Avocado Rice Bowl',
    calories: 540,
    protein: 0,
    portions: 1,
    mealType: MealType.lunch,
    description: 'Combine rice and vegetables in a bowl.\nAdd tuna and avocado.\nMix yogurt with lime juice and drizzle over the bowl.',
    ingredients: [
      Ingredient(
        name: 'canned tuna in water, drained',
        quantity: '120 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cooked rice',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'avocado',
        quantity: '60 g',
        calories: 540.00,
        protein: 0.00,
        carbs: 0.00,
        fat: 60.00,
        fiber: 0.00,
      ),
      Ingredient(
        name: 'cucumber',
        quantity: '100 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'carrot',
        quantity: '50 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'Greek yogurt',
        quantity: '1 tbsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
      Ingredient(
        name: 'lime juice',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Shrimp Quinoa Mediterranean Bowl',
    calories: 31,
    protein: 15,
    portions: 1,
    mealType: MealType.lunch,
    description: 'Cook shrimp until opaque.\nCombine quinoa, vegetables and chickpeas.\nTop with shrimp and yogurt mixed with lemon juice and olive oil.',
    ingredients: [
      Ingredient(
        name: 'cooked shrimp',
        quantity: '180 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cooked quinoa',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cucumber',
        quantity: '100 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'tomato',
        quantity: '100 g',
        calories: null,
        protein: 14.10,
        carbs: 43.50,
        fat: 2.97,
        fiber: 12.30,
      ),
      Ingredient(
        name: 'chickpeas',
        quantity: '40 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'Greek yogurt',
        quantity: '30 g',
        calories: 30.90,
        protein: 0.91,
        carbs: 1.12,
        fat: 2.45,
        fiber: 0.02,
      ),
      Ingredient(
        name: 'olive oil',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'lemon juice',
        quantity: '1 tbsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Lemon Garlic Chicken with Potatoes',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.dinner,
    description: 'Roast potatoes at 200 C for about 25 minutes.\nSeason chicken with garlic and lemon and bake or grill until cooked through.\nSteam broccoli.\nServe with potatoes and broccoli.',
    ingredients: [
      Ingredient(
        name: 'chicken breast',
        quantity: '170 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'baby potatoes',
        quantity: '220 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'broccoli',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'olive oil',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'garlic clove, minced',
        quantity: '1 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'lemon juice',
        quantity: '1 tbsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Baked Salmon Asparagus Quinoa',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.dinner,
    description: 'Place salmon and asparagus on a baking tray.\nSeason with lemon and oil.\nBake at 200 C until salmon is cooked through, about 12-15 minutes.\nServe with quinoa.',
    ingredients: [
      Ingredient(
        name: 'salmon',
        quantity: '170 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cooked quinoa',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'asparagus',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'olive oil',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'lemon juice',
        quantity: '1 tbsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Lean Beef Kofta Couscous',
    calories: 41,
    protein: 1,
    portions: 1,
    mealType: MealType.dinner,
    description: 'Mix beef with cumin, paprika and parsley and shape into small kofta.\nGrill or pan-cook until fully cooked.\nServe with couscous, salad and yogurt.',
    ingredients: [
      Ingredient(
        name: 'lean ground beef',
        quantity: '170 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cooked whole-wheat couscous',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cucumber-tomato salad',
        quantity: '100 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'Greek yogurt',
        quantity: '40 g',
        calories: 41.20,
        protein: 1.21,
        carbs: 1.49,
        fat: 3.26,
        fiber: 0.03,
      ),
      Ingredient(
        name: 'cumin',
        quantity: '0.5 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'paprika',
        quantity: '0.5 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'chopped parsley',
        quantity: '1 tbsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Chicken Vegetable Curry',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.dinner,
    description: 'Saute chicken in oil until lightly browned.\nAdd vegetables, curry powder and coconut milk.\nSimmer until chicken is cooked and sauce thickens.\nServe over rice.',
    ingredients: [
      Ingredient(
        name: 'chicken breast',
        quantity: '170 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cooked brown rice',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'mixed vegetables',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'light coconut milk',
        quantity: '100 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'curry powder',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
      Ingredient(
        name: 'olive oil',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Shrimp Fajitas',
    calories: 481,
    protein: 1,
    portions: 1,
    mealType: MealType.dinner,
    description: 'Season shrimp with cumin and paprika.\nCook peppers and onion in oil, then add shrimp and cook until opaque.\nFill tortillas with shrimp, vegetables, avocado and yogurt.',
    ingredients: [
      Ingredient(
        name: 'shrimp',
        quantity: '180 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'whole-grain tortillas',
        quantity: '2 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'bell peppers and onion',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'avocado',
        quantity: '50 g',
        calories: 450.00,
        protein: 0.00,
        carbs: 0.00,
        fat: 50.00,
        fiber: 0.00,
      ),
      Ingredient(
        name: 'Greek yogurt',
        quantity: '30 g',
        calories: 30.90,
        protein: 0.91,
        carbs: 1.12,
        fat: 2.45,
        fiber: 0.02,
      ),
      Ingredient(
        name: 'olive oil',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cumin',
        quantity: '0.5 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'paprika',
        quantity: '0.5 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Turkey Meatballs Whole-Wheat Pasta',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.dinner,
    description: 'Mix turkey with onion and garlic and form meatballs.\nBrown meatballs in oil, add passata and simmer until cooked.\nServe over pasta and finish with Parmesan.',
    ingredients: [
      Ingredient(
        name: 'lean ground turkey',
        quantity: '170 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cooked whole-wheat pasta',
        quantity: '160 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'tomato passata',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'onion, finely chopped',
        quantity: '30 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'garlic clove',
        quantity: '1 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'olive oil',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'grated Parmesan',
        quantity: '1 tbsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Grilled Chicken Hummus Tabbouleh',
    calories: 155,
    protein: 19,
    portions: 1,
    mealType: MealType.dinner,
    description: 'Grill seasoned chicken and slice.\nMix bulgur with tomato, cucumber, parsley, lemon and oil.\nServe with chicken and hummus.',
    ingredients: [
      Ingredient(
        name: 'chicken breast',
        quantity: '170 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'hummus',
        quantity: '60 g',
        calories: 154.80,
        protein: 4.84,
        carbs: 5.40,
        fat: 11.94,
        fiber: 3.11,
      ),
      Ingredient(
        name: 'cooked bulgur',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'tomato',
        quantity: '100 g',
        calories: null,
        protein: 14.10,
        carbs: 43.50,
        fat: 2.97,
        fiber: 12.30,
      ),
      Ingredient(
        name: 'cucumber',
        quantity: '80 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'parsley',
        quantity: '30 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'lemon juice',
        quantity: '1 tbsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'olive oil',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Baked Cod Sweet Potato Green Beans',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.dinner,
    description: 'Roast sweet potato at 200 C until tender.\nSeason cod with paprika and lemon and bake until opaque.\nSteam green beans and toss with oil.\nServe together.',
    ingredients: [
      Ingredient(
        name: 'cod fillet',
        quantity: '200 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'sweet potato',
        quantity: '220 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'green beans',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'olive oil',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'lemon juice',
        quantity: '1 tbsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'paprika',
        quantity: '0.5 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Beef Brown Rice Vegetable Bowl',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.dinner,
    description: 'Stir-fry beef in sesame oil.\nAdd vegetables and soy sauce and cook until tender-crisp.\nServe over brown rice.',
    ingredients: [
      Ingredient(
        name: 'lean beef strips',
        quantity: '160 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cooked brown rice',
        quantity: '160 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'mixed vegetables',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'sesame oil',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
      Ingredient(
        name: 'low-sodium soy sauce',
        quantity: '1 tbsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Moroccan Chicken Vegetable Tagine',
    calories: 2,
    protein: 0,
    portions: 1,
    mealType: MealType.dinner,
    description: 'Cut chicken into pieces and brown in oil.\nAdd vegetables, chickpeas and spices with a splash of water.\nCover and simmer until chicken and vegetables are tender.\nServe with couscous.',
    ingredients: [
      Ingredient(
        name: 'chicken breast',
        quantity: '170 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cooked couscous',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'mixed carrot, zucchini and tomato',
        quantity: '180 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'chickpeas',
        quantity: '40 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'olive oil',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cumin',
        quantity: '0.5 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'paprika',
        quantity: '0.5 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cinnamon',
        quantity: '0.25 tsp',
        calories: 1.68,
        protein: 0.03,
        carbs: 0.19,
        fat: 0.01,
        fiber: 0.37,
      ),
    ],
  ),
  Recipe(
    name: 'Greek Yogurt Berry Cup',
    calories: 251,
    protein: 8,
    portions: 1,
    mealType: MealType.snack,
    description: 'Add yogurt to a bowl.\nTop with berries and chia seeds.',
    ingredients: [
      Ingredient(
        name: 'Greek yogurt',
        quantity: '200 g',
        calories: 206.00,
        protein: 6.04,
        carbs: 7.46,
        fat: 16.32,
        fiber: 0.14,
      ),
      Ingredient(
        name: 'berries',
        quantity: '100 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'chia seeds',
        quantity: '10 g',
        calories: 45.40,
        protein: 1.65,
        carbs: 0.77,
        fat: 3.07,
        fiber: 3.44,
      ),
    ],
  ),
  Recipe(
    name: 'Apple Peanut Butter',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.snack,
    description: 'Slice apple.\nServe with peanut butter for dipping.',
    ingredients: [
      Ingredient(
        name: 'medium apple',
        quantity: '1 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'natural peanut butter',
        quantity: '20 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Cottage Cheese Cucumber Cup',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.snack,
    description: 'Dice cucumber.\nMix with cottage cheese and herbs.',
    ingredients: [
      Ingredient(
        name: 'low-fat cottage cheese',
        quantity: '180 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cucumber',
        quantity: '100 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'chopped herbs',
        quantity: '1 tbsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'Pinch black pepper',
        quantity: '',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Boiled Eggs and Fruit',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.snack,
    description: 'Boil eggs until yolks are set, about 9-11 minutes.\nPeel and serve with orange.',
    ingredients: [
      Ingredient(
        name: 'large eggs',
        quantity: '2 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'small orange',
        quantity: '1 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Hummus Crunch Plate',
    calories: 155,
    protein: 5,
    portions: 1,
    mealType: MealType.snack,
    description: 'Cut vegetables into sticks.\nServe with hummus.',
    ingredients: [
      Ingredient(
        name: 'hummus',
        quantity: '60 g',
        calories: 154.80,
        protein: 4.84,
        carbs: 5.40,
        fat: 11.94,
        fiber: 3.11,
      ),
      Ingredient(
        name: 'carrots',
        quantity: '100 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cucumber',
        quantity: '100 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'bell pepper',
        quantity: '50 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Berry Protein Smoothie',
    calories: 45,
    protein: 2,
    portions: 1,
    mealType: MealType.snack,
    description: 'Blend all ingredients until smooth.\nServe immediately.',
    ingredients: [
      Ingredient(
        name: 'skim milk',
        quantity: '200 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'berries',
        quantity: '100 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'whey protein',
        quantity: '20 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'chia seeds',
        quantity: '10 g',
        calories: 45.40,
        protein: 1.65,
        carbs: 0.77,
        fat: 3.07,
        fiber: 3.44,
      ),
    ],
  ),
  Recipe(
    name: 'Roasted Chickpeas',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.snack,
    description: 'Pat chickpeas dry and toss with oil and spices.\nRoast at 200 C for 25-30 minutes, shaking once.',
    ingredients: [
      Ingredient(
        name: 'cooked chickpeas',
        quantity: '120 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'olive oil',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'paprika',
        quantity: '0.5 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cumin',
        quantity: '0.25 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Tuna Whole-Grain Crackers',
    calories: 21,
    protein: 1,
    portions: 1,
    mealType: MealType.snack,
    description: 'Mix tuna, yogurt and lemon.\nServe with crackers.',
    ingredients: [
      Ingredient(
        name: 'canned tuna in water, drained',
        quantity: '80 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'whole-grain crackers',
        quantity: '25 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'Greek yogurt',
        quantity: '20 g',
        calories: 20.60,
        protein: 0.60,
        carbs: 0.75,
        fat: 1.63,
        fiber: 0.01,
      ),
      Ingredient(
        name: 'lemon juice',
        quantity: '1 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Almond Yogurt Cup',
    calories: 337,
    protein: 5,
    portions: 1,
    mealType: MealType.snack,
    description: 'Add yogurt to a bowl.\nTop with almonds, honey and cinnamon.',
    ingredients: [
      Ingredient(
        name: 'Greek yogurt',
        quantity: '170 g',
        calories: 175.10,
        protein: 5.13,
        carbs: 6.34,
        fat: 13.87,
        fiber: 0.12,
      ),
      Ingredient(
        name: 'almonds',
        quantity: '15 g',
        calories: 135.00,
        protein: 0.00,
        carbs: 0.00,
        fat: 15.00,
        fiber: 0.00,
      ),
      Ingredient(
        name: 'honey',
        quantity: '1 tsp',
        calories: 23.17,
        protein: 0.05,
        carbs: 5.75,
        fat: 0.00,
        fiber: 0.00,
      ),
      Ingredient(
        name: 'cinnamon',
        quantity: '0.5 tsp',
        calories: 3.35,
        protein: 0.06,
        carbs: 0.38,
        fat: 0.02,
        fiber: 0.73,
      ),
    ],
  ),
  Recipe(
    name: 'Banana Cottage Cheese Bowl',
    calories: 93,
    protein: 0,
    portions: 1,
    mealType: MealType.snack,
    description: 'Slice banana.\nCombine with cottage cheese and top with walnuts and cinnamon.',
    ingredients: [
      Ingredient(
        name: 'low-fat cottage cheese',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'small banana',
        quantity: '1 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cinnamon',
        quantity: '0.5 tsp',
        calories: 3.35,
        protein: 0.06,
        carbs: 0.38,
        fat: 0.02,
        fiber: 0.73,
      ),
      Ingredient(
        name: 'walnuts',
        quantity: '10 g',
        calories: 90.00,
        protein: 0.00,
        carbs: 0.00,
        fat: 10.00,
        fiber: 0.00,
      ),
    ],
  ),
  Recipe(
    name: 'Lemon Cucumber Mint Water',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Combine all ingredients in a jug.\nChill for 30 minutes and serve over ice.',
    ingredients: [
      Ingredient(
        name: 'cold water',
        quantity: '500 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'lemon, sliced',
        quantity: '0.5 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cucumber, sliced',
        quantity: '50 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'mint leaves',
        quantity: '6 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Ginger Lemon Water',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Steep ginger in hot water for 5-10 minutes.\nCool slightly, add lemon and serve.',
    ingredients: [
      Ingredient(
        name: 'water',
        quantity: '500 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
      Ingredient(
        name: 'fresh ginger, sliced',
        quantity: '10 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'lemon, juiced',
        quantity: '0.5 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Strawberry Mint Infused Water',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Combine ingredients in a jug.\nChill for 30-60 minutes and serve.',
    ingredients: [
      Ingredient(
        name: 'water',
        quantity: '500 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
      Ingredient(
        name: 'strawberries, sliced',
        quantity: '80 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'mint leaves',
        quantity: '6 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Orange Cucumber Water',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Add fruit and cucumber to water.\nChill for 30 minutes and serve.',
    ingredients: [
      Ingredient(
        name: 'water',
        quantity: '500 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
      Ingredient(
        name: 'orange slices',
        quantity: '3 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'cucumber, sliced',
        quantity: '50 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Lime Mint Sparkling Water',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Muddle mint lightly with lime juice.\nAdd sparkling water and ice.',
    ingredients: [
      Ingredient(
        name: 'unsweetened sparkling water',
        quantity: '400 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'lime, juiced',
        quantity: '1 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'mint leaves',
        quantity: '8 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Watermelon Basil Water',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Add watermelon and basil to water.\nChill for 30 minutes and serve.',
    ingredients: [
      Ingredient(
        name: 'water',
        quantity: '500 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
      Ingredient(
        name: 'watermelon cubes',
        quantity: '100 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'basil leaves',
        quantity: '4 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Ginger Turmeric Lemon Drink',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Warm water with ginger and turmeric for 5 minutes.\nStrain if desired and add lemon.',
    ingredients: [
      Ingredient(
        name: 'water',
        quantity: '300 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
      Ingredient(
        name: 'fresh ginger',
        quantity: '5 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'turmeric',
        quantity: '0.25 tsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
      Ingredient(
        name: 'lemon, juiced',
        quantity: '0.5 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Iced Green Tea Lemon',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Brew tea and let it cool.\nAdd lemon juice and ice.',
    ingredients: [
      Ingredient(
        name: 'brewed unsweetened green tea',
        quantity: '300 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'lemon juice',
        quantity: '1 tbsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'Ice',
        quantity: '',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
    ],
  ),
  Recipe(
    name: 'Hibiscus Lime Iced Tea',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Brew hibiscus tea and cool.\nAdd lime juice and ice.',
    ingredients: [
      Ingredient(
        name: 'unsweetened hibiscus tea',
        quantity: '300 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'lime juice',
        quantity: '1 tbsp',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'Ice',
        quantity: '',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
    ],
  ),
  Recipe(
    name: 'Cucumber Lime Ginger Water',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Combine ingredients.\nChill for 30 minutes and serve over ice.',
    ingredients: [
      Ingredient(
        name: 'water',
        quantity: '500 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
      Ingredient(
        name: 'cucumber',
        quantity: '70 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'lime, sliced',
        quantity: '0.5 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'fresh ginger',
        quantity: '5 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
    ],
  ),
  Recipe(
    name: 'Virgin Mojito',
    calories: 23,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Muddle mint with lime juice and honey.\nFill glass with ice and sparkling water.\nStir gently.',
    ingredients: [
      Ingredient(
        name: 'lime juice',
        quantity: '30 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'mint leaves',
        quantity: '8 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'sparkling water',
        quantity: '200 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'honey',
        quantity: '1 tsp',
        calories: 23.17,
        protein: 0.05,
        carbs: 5.75,
        fat: 0.00,
        fiber: 0.00,
      ),
      Ingredient(
        name: 'Ice',
        quantity: '',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
    ],
  ),
  Recipe(
    name: 'Berry Fizz',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Muddle berries with lime juice.\nAdd ice and sparkling water.\nStir and serve.',
    ingredients: [
      Ingredient(
        name: 'mixed berries',
        quantity: '80 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'lime juice',
        quantity: '20 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'sparkling water',
        quantity: '200 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'Ice',
        quantity: '',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
    ],
  ),
  Recipe(
    name: 'Pineapple Ginger Cooler',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Mix pineapple juice and lime juice.\nAdd ginger, ice and sparkling water.\nStir.',
    ingredients: [
      Ingredient(
        name: 'unsweetened pineapple juice',
        quantity: '100 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'lime juice',
        quantity: '10 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'fresh ginger',
        quantity: '5 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'sparkling water',
        quantity: '150 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'Ice',
        quantity: '',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
    ],
  ),
  Recipe(
    name: 'Cucumber Collins',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Blend or muddle cucumber and strain if desired.\nCombine with lemon juice and ice.\nTop with sparkling water.',
    ingredients: [
      Ingredient(
        name: 'cucumber',
        quantity: '80 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'lemon juice',
        quantity: '20 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'sparkling water',
        quantity: '200 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'mint leaves',
        quantity: '5 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'Ice',
        quantity: '',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
    ],
  ),
  Recipe(
    name: 'Passion Fruit Spritz',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Combine passion fruit and lime.\nAdd ice and sparkling water.\nStir gently.',
    ingredients: [
      Ingredient(
        name: 'passion fruit pulp',
        quantity: '80 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'lime juice',
        quantity: '15 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'sparkling water',
        quantity: '200 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'Ice',
        quantity: '',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
    ],
  ),
  Recipe(
    name: 'Watermelon Mint Cooler',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Blend watermelon with lime.\nPour over ice, add mint and sparkling water.\nStir.',
    ingredients: [
      Ingredient(
        name: 'watermelon',
        quantity: '150 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'lime juice',
        quantity: '10 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'mint leaves',
        quantity: '6 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'sparkling water',
        quantity: '150 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'Ice',
        quantity: '',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
    ],
  ),
  Recipe(
    name: 'Strawberry Basil Smash',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Muddle strawberries, basil and lemon.\nAdd ice and sparkling water.\nStir and serve.',
    ingredients: [
      Ingredient(
        name: 'strawberries',
        quantity: '100 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'lemon juice',
        quantity: '10 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'basil leaves',
        quantity: '4 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'sparkling water',
        quantity: '150 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'Ice',
        quantity: '',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
    ],
  ),
  Recipe(
    name: 'Mango Lime Fizz',
    calories: 52,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Blend mango with lime juice and a splash of water.\nPour over ice and top with sparkling water.',
    ingredients: [
      Ingredient(
        name: 'mango',
        quantity: '100 g',
        calories: 52.10,
        protein: 0.21,
        carbs: 11.30,
        fat: 0.08,
        fiber: 0.16,
      ),
      Ingredient(
        name: 'lime juice',
        quantity: '15 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'sparkling water',
        quantity: '150 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'Ice',
        quantity: '',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
    ],
  ),
  Recipe(
    name: 'Pomegranate Citrus Spritz',
    calories: 0,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Combine juices.\nAdd ice and sparkling water.\nStir gently.',
    ingredients: [
      Ingredient(
        name: 'unsweetened pomegranate juice',
        quantity: '80 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'orange juice',
        quantity: '30 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'sparkling water',
        quantity: '150 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'Ice',
        quantity: '',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
    ],
  ),
  Recipe(
    name: 'Peach Ginger Iced Tea',
    calories: 40,
    protein: 0,
    portions: 1,
    mealType: MealType.breakfast,
    description: 'Blend peach with a little tea.\nCombine with remaining tea and ginger.\nServe over ice.',
    ingredients: [
      Ingredient(
        name: 'unsweetened black tea, chilled',
        quantity: '150 ml',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'peach',
        quantity: '80 g',
        calories: 40.24,
        protein: 0.18,
        carbs: 9.68,
        fat: 0.04,
        fiber: 0.26,
      ),
      Ingredient(
        name: 'fresh ginger',
        quantity: '5 g',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
        needsConfirmation: true,
      ),
      Ingredient(
        name: 'Ice',
        quantity: '',
        calories: null,
        protein: null,
        carbs: null,
        fat: null,
        fiber: null,
      ),
    ],
  ),
];
